export enum InjectionTokens {
	USER_REPOSITORY = "USER_REPOSITORY",
	USER_SERVICE = "USER_SERVICE",
	USER_CONTROLLER = "USER_CONTROLLER",

	ACCOUNT_SERVICE = "ACCOUNT_SERVICE",
	ACCOUNT_REPOSITORY = "ACCOUNT_REPOSITORY",
	ACCOUNT_CONTROLLER = "ACCOUNT_CONTROLLER",
}
